# Generated by Django 5.2.6 on 2025-09-29 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_announcement_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('link', models.URLField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('is_verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='transaction',
            name='state',
            field=models.IntegerField(choices=[(1, "To'lov yaratildi. Tasdiqlanishi kutilmoqda"), (2, "To'lov muvafaqqiyatli amalga oshirildi"), (-1, "To'lov bekor qilindi"), (-2, "To'lov tugallangandan keyin qaytarildi."), (3, 'Yechib olindi')]),
        ),
    ]
