# Generated by Django 5.2.6 on 2025-09-29 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_user_telegram_username_alter_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='link',
        ),
    ]
