# Generated by Django 5.2.6 on 2025-10-01 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_advertisement_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='receivers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='status',
            field=models.CharField(choices=[('sending', 'Yuborilmoqda...'), ('sended', 'Yuborilgan')], default='sending', max_length=100),
        ),
    ]
