# Generated by Django 5.2.6 on 2025-10-01 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_advertisement_receivers_advertisement_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='content',
            field=models.TextField(verbose_name='Matn'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='receivers',
            field=models.IntegerField(default=0, verbose_name='Qabul qilganlar'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='status',
            field=models.CharField(choices=[('sending', 'Yuborilmoqda...'), ('sended', 'Yuborilgan')], default='sending', max_length=100, verbose_name='Holati'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='content',
            field=models.TextField(verbose_name='Matn'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Tasdiqlangan'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Nomi'),
        ),
        migrations.AlterField(
            model_name='user',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100, verbose_name='Balans'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ism'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Familiya'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('teacher', "O'qituvchi"), ('student', 'Talaba')], default='student', max_length=20, verbose_name='ROLE'),
        ),
    ]
