# Generated by Django 5.2.6 on 2025-10-24 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='count',
            name='created',
            field=models.DateField(auto_now=True),
        ),
    ]
