# Generated by Django 5.2.6 on 2026-02-01 17:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_count_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handle', models.CharField(max_length=100, verbose_name='Link')),
                ('name', models.CharField(max_length=1000, verbose_name='Nomi')),
                ('logo', models.ImageField(upload_to='images/course_channels', verbose_name='Logo')),
                ('likers', models.ManyToManyField(editable=False, related_name='course_channel_likers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
